package wsnotify

const (
	WS_IO_STATUS  = "WS_IO_STATUS"
	WS_IO_CONTACT = "WS_IO_CONTACT"
	WS_IO_SET     = "WS_IO_SET"

	WS_DEVICE_STATUS = "WS_DEVICE_STATUS"

	WS_READER_UID = "WS_READER_UID"

	WS_SCANNER_READ = "WS_SCANNER_READ"

	WS_ORDER_LIST             = "WS_ORDER_LIST"
	WS_ORDER_DETAIL           = "WS_ORDER_DETAIL"
	WS_ORDER_UPDATE           = "WS_ORDER_UPDATE"
	WS_ORDER_DATA_UPDATE      = "WS_ORDER_DATA_UPDATE"
	WS_ORDER_STEP_UPDATE      = "WS_ORDER_STEP_UPDATE"
	WS_ORDER_STEP_DATA_UPDATE = "WS_ORDER_STEP_DATA_UPDATE"
	WS_ORDER_DETAIL_BY_CODE   = "WS_ORDER_DETAIL_BY_CODE"
	WS_ORDER_START            = "WS_ORDER_START"
	WS_ORDER_FINISH           = "WS_ORDER_FINISH"

	// tightening tool
	WS_TIGHTENING_DEVICE = "WS_TIGHTENING_DEVICE"

	WS_TOOL_JOB         = "WS_TOOL_JOB"
	WS_TOOL_PSET        = "WS_TOOL_PSET"
	WS_TOOL_PSET_BATCH  = "WS_TOOL_PSET_BATCH"
	WS_TOOL_RESULT      = "WS_TOOL_RESULT"
	WS_TOOL_ENABLE      = "WS_TOOL_ENABLE"
	WS_TOOL_MODE_SELECT = "WS_TOOL_MODE_SELECT"
	WS_TOOL_PSET_LIST   = "WS_TOOL_PSET_LIST"
	WS_TOOL_PSET_DETAIL = "WS_TOOL_PSET_DETAIL"
	WS_TOOL_JOB_LIST    = "WS_TOOL_JOB_LIST"
	WS_TOOL_JOB_DETAIL  = "WS_TOOL_JOB_DETAIL"

	WS_TIGHTENING_RESULT             = "WS_TIGHTENING_RESULT"
	WS_TIGHTENING_CONTROLLER_STATUS  = "WS_TIGHTENING_CONTROLLER_STATUS"
	WS_TIGHTENING_CONTROLLER_IO      = "WS_TIGHTENING_CONTROLLER_IO"
	WS_TIGHTENING_CONTROLLER_BARCODE = "WS_TIGHTENING_CONTROLLER_BARCODE"
	WS_TIGHTENING_TOOL_STATUS        = "WS_TIGHTENING_TOOL_STATUS"
)
