// @flow
export const SCANNER = {
  DEVICE_NOT_FOUND: 'SCANNER_DEVICE_NOT_FOUND',
  START_ERROR: 'SCANNER_START_ERROR',
  READ_ERROR: 'SCANNER_READ_ERROR',
  READ_NEW_DATA: 'SCANNER_NEW_DATA'
};

export const CARD_AUTH = {
  READER: {
    INSERTED: 'CARD_AUTH_READER_INSERTED',
    REMOVED: 'CARD_AUTH_READER_REMOVED'
  },
  CARD: {
    INSERTED: 'CARD_AUTH_CARD_INSERTED',
    REMOVED: 'CARD_AUTH_CARD_REMOVED',
    READ: {
      STARTED: 'CARD_AUTH_CARD_READ_STARTED',
      SUCCESS: 'CARD_AUTH_CARD_READ_SUCCESS',
      FAILURE: 'CARD_AUTH_CARD_READ_FAILURE'
    }
  },
  ERROR: 'CARD_AUTH_ERROR'
};

export const USER = {
  FETCH_OK: 'USER_FETCH_OK',
};

export const RUSH = {
  NEW_RESULTS: 'RUSH_NEW_RESULTS',
};

export const OPERATION = {
  OPERATION: {
    FETCH_OK: 'OPERATION_OPERATION_FETCH_OK',
    FETCH_FAIL: 'OPERATION_OPERATION_FETCH_FAIL',
  },
  PROGRAMME: {
    SET_OK: 'OPERATION_PROGRAMME_SET_OK',
    SET_FAIL: 'OPERATION_PROGRAMME_SET_FAIL'
  },
  TRIGGER: {
    NEW_DATA: 'OPERATION_TRIGGER_NEW_DATA'
  },
  RESULT: {
    OK: 'OPERATION_RESULT_OK',
    NOK: 'OPERATION_RESULT_NOK',
  },
  STARTED: 'OPERATION_STARTED',
  FINISHED: 'OPERATION_FINISHED',
  FAILED: 'OPERATION_FAILED',
};

export const CONNECTION = {
  FETCH_OK: 'CONNECTION_FETCH_OK',
  FETCH_FAIL: 'CONNECTION_FETCH_FAIL',
};

export const NOTIFY = {
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  CLOSE: 'CLOSE_NOTIFICATION'
};

export const SYSTEM_INIT = 'SYSTEM_INIT';

export const SET_HEALTHZ_CHECK = 'SET_HEALTHZ_CHECK';

export const WORK_MODE = {
  SWITCH_WM: 'SWITCH_WORK_MODE',
  SWITCH_CM: 'SWITCH_CONTROL_MODE'
};

e;
