// @flow
export const SCANNER = {
  DEVICE_NOT_FOUND: 'SCANNER_DEVICE_NOT_FOUND',
  START_ERROR: 'SCANNER_START_ERROR',
  READ_ERROR: 'SCANNER_READ_ERROR',
  READ_NEW_DATA: 'SCANNER_NEW_DATA'
};

export const CARD_AUTH = {
  READER: {
    INSERTED: 'CARD_AUTH_READER_INSERTED',
    REMOVED: 'CARD_AUTH_READER_REMOVED'
  },
  CARD: {
    INSERTED: 'CARD_AUTH_CARD_INSERTED',
    REMOVED: 'CARD_AUTH_CARD_REMOVED',
    READ: {
      STARTED: 'CARD_AUTH_CARD_READ_STARTED',
      SUCCESS: 'CARD_AUTH_CARD_READ_SUCCESS',
      FAILURE: 'CARD_AUTH_CARD_READ_FAILURE'
    }
  },
  ERROR: 'CARD_AUTH_ERROR'
};

export const NOTIFY = {
  NEW_NOTIFICATION: 'NEW_NOTIFICATION',
  CLOSE: 'CLOSE_NOTIFICATION'
};

export const SYSTEM_INIT = 'SYSTEM_INIT';

export const SET_HEALTHZ_CHECK = 'SET_HEALTHZ_CHECK';

export const WORK_MODE = {
  SWITCH_WM: 'SWITCH_WORK_MODE',
  SWITCH_CM: 'SWITCH_CONTROL_MODE'
};

e;
