// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aiis.proto

package aiis

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_957c5705f8b44706, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*Payload)(nil), "aiis.Payload")
}

func init() { proto.RegisterFile("aiis.proto", fileDescriptor_957c5705f8b44706) }

var fileDescriptor_957c5705f8b44706 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcc, 0xcc, 0x2c,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x94, 0xb9, 0xd8, 0x03, 0x12,
	0x2b, 0x73, 0xf2, 0x13, 0x53, 0x84, 0x24, 0xb8, 0xd8, 0x0b, 0x20, 0x4c, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xce, 0x20, 0x18, 0xd7, 0xc8, 0x82, 0x8b, 0x3d, 0x28, 0xc0, 0xd9, 0x31, 0x33, 0xb3, 0x58,
	0x48, 0x17, 0xcc, 0xf4, 0xcb, 0x4f, 0x49, 0x15, 0xe2, 0xd5, 0x03, 0x9b, 0x06, 0xd5, 0x2e, 0x85,
	0xca, 0x55, 0x62, 0xd0, 0x60, 0x34, 0x60, 0x4c, 0x62, 0x03, 0xdb, 0x65, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x99, 0x89, 0xf6, 0x00, 0x79, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCAiisClient is the client API for RPCAiis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCAiisClient interface {
	RPCNode(ctx context.Context, opts ...grpc.CallOption) (RPCAiis_RPCNodeClient, error)
}

type rPCAiisClient struct {
	cc *grpc.ClientConn
}

func NewRPCAiisClient(cc *grpc.ClientConn) RPCAiisClient {
	return &rPCAiisClient{cc}
}

func (c *rPCAiisClient) RPCNode(ctx context.Context, opts ...grpc.CallOption) (RPCAiis_RPCNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RPCAiis_serviceDesc.Streams[0], "/aiis.RPCAiis/RPCNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &rPCAiisRPCNodeClient{stream}
	return x, nil
}

type RPCAiis_RPCNodeClient interface {
	Send(*Payload) error
	Recv() (*Payload, error)
	grpc.ClientStream
}

type rPCAiisRPCNodeClient struct {
	grpc.ClientStream
}

func (x *rPCAiisRPCNodeClient) Send(m *Payload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rPCAiisRPCNodeClient) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RPCAiisServer is the server API for RPCAiis service.
type RPCAiisServer interface {
	RPCNode(RPCAiis_RPCNodeServer) error
}

func RegisterRPCAiisServer(s *grpc.Server, srv RPCAiisServer) {
	s.RegisterService(&_RPCAiis_serviceDesc, srv)
}

func _RPCAiis_RPCNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RPCAiisServer).RPCNode(&rPCAiisRPCNodeServer{stream})
}

type RPCAiis_RPCNodeServer interface {
	Send(*Payload) error
	Recv() (*Payload, error)
	grpc.ServerStream
}

type rPCAiisRPCNodeServer struct {
	grpc.ServerStream
}

func (x *rPCAiisRPCNodeServer) Send(m *Payload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rPCAiisRPCNodeServer) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _RPCAiis_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aiis.RPCAiis",
	HandlerType: (*RPCAiisServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RPCNode",
			Handler:       _RPCAiis_RPCNode_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "aiis.proto",
}
