package dispatcherBus

//todo: 通过封装getattr, setattr 减少这种赋值代码
const (
	DISPATCHER_WS_IO_STATUS  = "WS_IO_STATUS"
	DISPATCHER_WS_IO_CONTACT = "WS_IO_CONTACT"
	DISPATCHER_WS_IO_SET     = "WS_IO_SET"

	DISPATCHER_WS_DEVICE_STATUS = "WS_DEVICE_STATUS"

	DISPATCHER_WS_ORDER_LIST             = "WS_ORDER_LIST"
	DISPATCHER_WS_ORDER_DETAIL           = "WS_ORDER_DETAIL"
	DISPATCHER_WS_ORDER_UPDATE           = "WS_ORDER_UPDATE"
	DISPATCHER_WS_ORDER_STEP_UPDATE      = "WS_ORDER_STEP_UPDATE"
	DISPATCHER_WS_ORDER_STEP_DATA_UPDATE = "WS_ORDER_STEP_DATA_UPDATE"
	DISPATCHER_WS_ORDER_DETAIL_BY_CODE   = "WS_ORDER_DETAIL_BY_CODE"

	//SCANNER
	DISPATCHER_SCANNER_ON_RECV = "SCANNER_ON_RECV"

	//tightening Device
	DISPATCH_RESULT_PREVIEW            = "DISPATCH_RESULT_PREVIEW"
	DISPATCH_RESULT                    = "DISPATCH_RESULT"
	DISPATCH_CURVE                     = "DISPATCH_CURVE"
	DISPATCH_IO_PREVIEW                = "DISPATCH_IO_PREVIEW"
	DISPATCH_IO                        = "DISPATCH_IO"
	DISPATCH_CONTROLLER_STATUS_PREVIEW = "DISPATCH_CONTROLLER_STATUS_PREVIEW"
	DISPATCH_CONTROLLER_STATUS         = "DISPATCH_CONTROLLER_STATUS"
	DISPATCH_TOOL_STATUS_PREVIEW       = "DISPATCH_TOOL_STATUS_PREVIEW"
	DISPATCH_TOOL_STATUS               = "DISPATCH_TOOL_STATUS"
	DISPATCH_CONTROLLER_ID_PREVIEW     = "DISPATCH_CONTROLLER_ID_PREVIEW"
	DISPATCH_CONTROLLER_ID             = "DISPATCH_CONTROLLER_ID"
	DISPATCH_NEW_TOOL                  = "DISPATCH_NEW_TOOL"

	// tightening tool
	WS_TIGHTENING_DEVICE = "WS_TIGHTENING_DEVICE"

	WS_TOOL_JOB         = "WS_TOOL_JOB"
	WS_TOOL_PSET        = "WS_TOOL_PSET"
	WS_TOOL_RESULT      = "WS_TOOL_RESULT"
	WS_TOOL_ENABLE      = "WS_TOOL_ENABLE"
	WS_TOOL_MODE_SELECT = "WS_TOOL_MODE_SELECT"
	WS_TOOL_PSET_LIST   = "WS_TOOL_PSET_LIST"
	WS_TOOL_PSET_DETAIL = "WS_TOOL_PSET_DETAIL"
	WS_TOOL_JOB_LIST    = "WS_TOOL_JOB_LIST"
	WS_TOOL_JOB_DETAIL  = "WS_TOOL_JOB_DETAIL"

	WS_TIGHTENING_RESULT             = "WS_TIGHTENING_RESULT"
	WS_TIGHTENING_CONTROLLER_STATUS  = "WS_TIGHTENING_CONTROLLER_STATUS"
	WS_TIGHTENING_CONTROLLER_IO      = "WS_TIGHTENING_CONTROLLER_IO"
	WS_TIGHTENING_CONTROLLER_BARCODE = "WS_TIGHTENING_CONTROLLER_BARCODE"
	WS_TIGHTENING_TOOL_STATUS        = "WS_TIGHTENING_TOOL_STATUS"

	// aiis
	DISPATCH_ODOO_STATUS = "DISPATCH_ODOO_STATUS"
	DISPATCH_AIIS_STATUS = "DISPATCH_AIIS_STATUS"

	DISPATCH_RPC_STATUS = "DISPATCH_RPC_STATUS"
	DISPATCH_RPC_RECV   = "DISPATCH_RPC_RECV"

	//broker
	DISPATCH_BROKER_STATUS = "DISPATCH_BROKER_STATUS"
)
