package dispatcherBus

//todo: 通过封装getattr, setattr 减少这种赋值代码
const (
	DISPATCHER_WS_IO_STATUS  = "WS_IO_STATUS"
	DISPATCHER_WS_IO_CONTACT = "WS_IO_CONTACT"
	DISPATCHER_WS_IO_SET     = "WS_IO_SET"

	DISPATCHER_WS_DEVICE_STATUS = "WS_DEVICE_STATUS"

	DISPATCHER_WS_ORDER_LIST             = "WS_ORDER_LIST"
	DISPATCHER_WS_ORDER_DETAIL           = "WS_ORDER_DETAIL"
	DISPATCHER_WS_ORDER_UPDATE           = "WS_ORDER_UPDATE"
	DISPATCHER_WS_ORDER_STEP_UPDATE      = "WS_ORDER_STEP_UPDATE"
	DISPATCHER_WS_ORDER_STEP_DATA_UPDATE = "WS_ORDER_STEP_DATA_UPDATE"
	DISPATCHER_WS_ORDER_DETAIL_BY_CODE   = "WS_ORDER_DETAIL_BY_CODE"

	//SCANNER
	DISPATCHER_SCANNER_ON_RECV = "SCANNER_ON_RECV"
)
