// @flow

const CARD_AUTH = {
  READER: {
    INSERTED: 'CARD_AUTH_READER_INSERTED',
    REMOVED: 'CARD_AUTH_READER_REMOVED'
  },
  CARD: {
    INSERTED: 'CARD_AUTH_CARD_INSERTED',
    REMOVED: 'CARD_AUTH_CARD_REMOVED',
    READ_DATA: {
      STARTED: 'CARD_AUTH_CARD_READ_STARTED',
      SUCCESS: 'CARD_AUTH_CARD_READ_SUCCESS',
      FAILURE: 'CARD_AUTH_CARD_READ_FAILURE'
    }
  },
  ERROR: 'CARD_AUTH_ERROR'
};

export default CARD_AUTH;
