// @flow

// 工单状态
export const ORDER_STATUS = Object.freeze({
  TODO: 'todo',
  WIP: 'wip',
  DONE: 'done',
  CANCEL: 'cancel',
  PENDING: 'pending',
  FAIL: 'fail'
});

// rush type
export const ORDER_WS_TYPES = Object.freeze({
  LIST: 'WS_ORDER_LIST',
  DETAIL: 'WS_ORDER_DETAIL',
  UPDATE: 'WS_ORDER_UPDATE',
  STEP_UPDATE: 'WS_ORDER_STEP_UPDATE',
  NEW: 'WS_NEW_ORDER',
  START_REQUEST: 'WS_ORDER_START_REQUEST',
  FINISH_REQUEST: 'WS_ORDER_FINISH_REQUEST',
  STEP_DATA: 'WS_ORDER_STEP_DATA_UPDATE',
  ORDER_DATA: 'WS_WORKORDER_DATA_UPDATE',
  ORDER_DETAIL_BY_CODE: 'WS_ORDER_DETAIL_BY_CODE'
});

// order action types
export const ORDER = Object.freeze({
  TRY_WORK_ON: 'ORDER_TRY_WORK_ON',
  WORK_ON: 'ORDER_WORK_ON',
  SET_WORKING: 'ORDER_SET_WORKING',
  TRY_VIEW: 'ORDER_TRY_VIEW',
  VIEW: 'ORDER_VIEW',
  FINISH: 'ORDER_FINISH',
  DID_FINISH: 'ORDER_DID_FINISH',
  // update the store
  UPDATE_STATE: 'ORDER_UPDATE_STATE',
  NEW_LIST: 'ORDER_NEW_LIST',
  NEW_SCANNER: 'ORDER_NEW_SCANNER',
  REPORT_FINISH: 'ORDER_REPORT_FINISH',
  LIST: {
    GET: 'ORDER_LIST_GET',
    FAIL: 'ORDER_LIST_FAIL',
    SUCCESS: 'ORDER_LIST_SUCCESS'
  },
  DETAIL: {
    GET: 'ORDER_DETAIL_GET',
    SUCCESS: 'ORDER_DETAIL_SUCCESS',
    FAIL: 'ORDER_DETAIL_FAIL'
  },
  STEP: {
    // 仅移动指针，不修改step状态
    NEXT: 'ORDER_STEP_NEXT', // 防抖前事件
    PREVIOUS: 'ORDER_STEP_PREVIOUS', // 防抖前事件
    VIEW_PREVIOUS: 'ORDER_STEP_VIEW_PREVIOUS', // 防抖后事件
    VIEW_NEXT: 'ORDER_STEP_VIEW_NEXT', // 防抖后事件

    JUMP_TO: 'ORDER_STEP_JUMP_TO',
    // 修改step的状态
    STATUS: 'ORDER_STEP_STATUS',
    // 步进、步退
    DO_PREVIOUS: 'ORDER_STEP_DO_PREVIOUS',
    FINISH: 'ORDER_STEP_FINISH'
  }
});
